//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BongrimWallpaper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("맑은 고딕, 20pt")]
        public global::System.Drawing.Font dateFont {
            get {
                return ((global::System.Drawing.Font)(this["dateFont"]));
            }
            set {
                this["dateFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyy년 MM월 dd일")]
        public string dateFormat {
            get {
                return ((string)(this["dateFormat"]));
            }
            set {
                this["dateFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color dateColor {
            get {
                return ((global::System.Drawing.Color)(this["dateColor"]));
            }
            set {
                this["dateColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float dateX {
            get {
                return ((float)(this["dateX"]));
            }
            set {
                this["dateX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float dateY {
            get {
                return ((float)(this["dateY"]));
            }
            set {
                this["dateY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool dateVisible {
            get {
                return ((bool)(this["dateVisible"]));
            }
            set {
                this["dateVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("맑은 고딕, 32pt")]
        public global::System.Drawing.Font mealTitleFont {
            get {
                return ((global::System.Drawing.Font)(this["mealTitleFont"]));
            }
            set {
                this["mealTitleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("맑은 고딕, 22pt")]
        public global::System.Drawing.Font mealContentFont {
            get {
                return ((global::System.Drawing.Font)(this["mealContentFont"]));
            }
            set {
                this["mealContentFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float mealContentSpace {
            get {
                return ((float)(this["mealContentSpace"]));
            }
            set {
                this["mealContentSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color mealTitleColor {
            get {
                return ((global::System.Drawing.Color)(this["mealTitleColor"]));
            }
            set {
                this["mealTitleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color mealContentColor {
            get {
                return ((global::System.Drawing.Color)(this["mealContentColor"]));
            }
            set {
                this["mealContentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mealAlignment {
            get {
                return ((int)(this["mealAlignment"]));
            }
            set {
                this["mealAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mealLayout {
            get {
                return ((int)(this["mealLayout"]));
            }
            set {
                this["mealLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float mealX {
            get {
                return ((float)(this["mealX"]));
            }
            set {
                this["mealX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float mealY {
            get {
                return ((float)(this["mealY"]));
            }
            set {
                this["mealY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mealVisible {
            get {
                return ((bool)(this["mealVisible"]));
            }
            set {
                this["mealVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("맑은 고딕, 72pt")]
        public global::System.Drawing.Font classMainFont {
            get {
                return ((global::System.Drawing.Font)(this["classMainFont"]));
            }
            set {
                this["classMainFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("맑은 고딕, 50pt")]
        public global::System.Drawing.Font classSubFont {
            get {
                return ((global::System.Drawing.Font)(this["classSubFont"]));
            }
            set {
                this["classSubFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color classMainColor {
            get {
                return ((global::System.Drawing.Color)(this["classMainColor"]));
            }
            set {
                this["classMainColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color classSubColor {
            get {
                return ((global::System.Drawing.Color)(this["classSubColor"]));
            }
            set {
                this["classSubColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int classAlignment {
            get {
                return ((int)(this["classAlignment"]));
            }
            set {
                this["classAlignment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float classX {
            get {
                return ((float)(this["classX"]));
            }
            set {
                this["classX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float classY {
            get {
                return ((float)(this["classY"]));
            }
            set {
                this["classY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool classVisible {
            get {
                return ((bool)(this["classVisible"]));
            }
            set {
                this["classVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string backgroundPath {
            get {
                return ((string)(this["backgroundPath"]));
            }
            set {
                this["backgroundPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string timetablePath {
            get {
                return ((string)(this["timetablePath"]));
            }
            set {
                this["timetablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public float mealSpace {
            get {
                return ((float)(this["mealSpace"]));
            }
            set {
                this["mealSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("맑은 고딕, 32pt")]
        public global::System.Drawing.Font listSubjectFont {
            get {
                return ((global::System.Drawing.Font)(this["listSubjectFont"]));
            }
            set {
                this["listSubjectFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("맑은 고딕, 25pt")]
        public global::System.Drawing.Font listTeacherFont {
            get {
                return ((global::System.Drawing.Font)(this["listTeacherFont"]));
            }
            set {
                this["listTeacherFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color listSubjectColor {
            get {
                return ((global::System.Drawing.Color)(this["listSubjectColor"]));
            }
            set {
                this["listSubjectColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color listSubjectAccentColor {
            get {
                return ((global::System.Drawing.Color)(this["listSubjectAccentColor"]));
            }
            set {
                this["listSubjectAccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color listTeacherColor {
            get {
                return ((global::System.Drawing.Color)(this["listTeacherColor"]));
            }
            set {
                this["listTeacherColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color listTeacherAccentColor {
            get {
                return ((global::System.Drawing.Color)(this["listTeacherAccentColor"]));
            }
            set {
                this["listTeacherAccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int listLayout {
            get {
                return ((int)(this["listLayout"]));
            }
            set {
                this["listLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool listVisible {
            get {
                return ((bool)(this["listVisible"]));
            }
            set {
                this["listVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float listX {
            get {
                return ((float)(this["listX"]));
            }
            set {
                this["listX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float listY {
            get {
                return ((float)(this["listY"]));
            }
            set {
                this["listY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float listSpace {
            get {
                return ((float)(this["listSpace"]));
            }
            set {
                this["listSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool listTeacherVisible {
            get {
                return ((bool)(this["listTeacherVisible"]));
            }
            set {
                this["listTeacherVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("맑은 고딕, 32pt")]
        public global::System.Drawing.Font weekFont {
            get {
                return ((global::System.Drawing.Font)(this["weekFont"]));
            }
            set {
                this["weekFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color weekColor {
            get {
                return ((global::System.Drawing.Color)(this["weekColor"]));
            }
            set {
                this["weekColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float weekX {
            get {
                return ((float)(this["weekX"]));
            }
            set {
                this["weekX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float weekY {
            get {
                return ((float)(this["weekY"]));
            }
            set {
                this["weekY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection students {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["students"]));
            }
            set {
                this["students"] = value;
            }
        }
    }
}
